version: '3'
services:
  postgres:
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    expose:
      - '5432'
  development-server:
    build:
      context: .
      dockerfile: ./docker/development/Dockerfile
    command: npm run dev
    ports:
      - "3333:3333"
      - "8080:8080"
    volumes:
      - .:/app